site_name: DE3- TBD

nav:
    - Getting Started: intro.md
    - Project Proposal: projectproposal.md
    - Project Development: projectdevelopment.md
    - Evaluation: evaluation.md
    - About: about.md

theme: readthedocs

